Python/Django/booklover/apps/books/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^/new', views.new, name="new"),
    url(r'^/create', views.createBook, name="create"),
    url(r'^/(?P<bookid>\d+)/addreview', views.addReview, name="addReview"),
    url(r'^/(?P<bookid>\d+)/show', views.show, name="show"),
    url(r'^/(?P<bookid>\d+)/(?P<reviewid>\d+)/destroy', views.deleteReview, name="destroy"),
    url(r'^', views.index, name="index"),
    # url(r'^update/', views.update, name="update"),
    # url(r'^success/', views.success, name="success"),
    # url(r'^edit/', views.edit, name="edit"),
]


# /(?P<bookid>\d+)

Python/Django/booklover/apps/users/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    # url(r'^new/', views.new, name="new"),
    url(r'^create/', views.create, name="create"),
    # url(r'^(?P<userid>\d+)/edit/', views.edit, name="edit"),
    url(r'^(?P<userid>\d+)/show', views.show, name="show"),
    # url(r'^(?P<userid>\d+)/update/', views.update, name="update"),
    # url(r'^(?P<userid>\d+)/destroy/', views.destroy, name="destroy"),
    url(r'^login/', views.login, name="login"),
    url(r'^success/', views.success, name="success"),
    url(r'^logout/', views.logout, name="logout"),
    url(r'^', views.index, name="index"),
]


# (?P<userid>\d+)

Python/Django/booklover/booklover/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin', admin.site.urls),
    url(r'^books', include('apps.books.urls', namespace="books")),
    url(r'^', include('apps.users.urls', namespace="main")),
]

Python/Django/booklover/apps/books/models.py
from django.db import models
from ..users.models import User


class authorManager(models.Manager):

    def authorValidate(self, authorInfo):
        errors = []

        if authorInfo['existingauthors'] == "addauthor" and len(authorInfo['newauthor']) < 1:
            errors.append("The author's name cannot be empty.")

        if authorInfo['existingauthors'] != 'addauthor':
            if len(authorInfo['newauthor']) > 0:
                errors.append('Unable to add a new author. Please set author dropdown to --add a new author--.')
        
        if authorInfo['existingauthors'] == 'addauthor':
            if authorInfo['newauthor']:
                if self.filter(name=authorInfo['newauthor']):
                    errors.append("That author already exists")

        return errors


    def addAuthor(self, authorInfo):
        self.create(name=authorInfo['name'])

class bookManager(models.Manager):
    
    def bookValidate(self, bookInfo):
        errors = []

        if len(bookInfo['title']) < 1:
            errors.append("The book title cannot be empty.")
        if self.filter(title__contains=bookInfo['title']):
            errors.append("This book is already in the database")
        
        return errors

    def addBook(self, bookInfo):
        self.create(title=bookInfo['title'], author=Author.objects.get(name=bookInfo['author']))



class reviewManager(models.Manager):
    
    def reviewValidate(self, reviewInfo):
        errors = []

        if len(reviewInfo['review']) < 1:
            errors.append("You must enter a review to add a book.")


        return errors

    def addReview(self,reviewInfo):
        
        self.create(reviewer=User.objects.get(id=reviewInfo['reviewer']), book=reviewInfo['book'], rating=reviewInfo['rating'], review=reviewInfo['review']) 

    def recentReviews(self):
        recentReviews = self.all().order_by("-created_at")[:3]
        
        return recentReviews

    def deleteReview(self, reviewid):
        goodbyeReview = self.get(id=reviewid)
        goodbyeReview.delete()



class Author(models.Model):
    name = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = authorManager()

class Book(models.Model):
    title = models.CharField(max_length=255)
    author = models.ForeignKey(Author, related_name="books")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = bookManager()


class Review(models.Model):
    reviewer = models.ForeignKey(User, related_name="reviews")
    book = models.ForeignKey(Book, related_name="reviews")
    rating = models.IntegerField()
    review = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = reviewManager()

Python/Django/booklover/apps/books/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import Author, Book, Review
from ..users.models import User

def index(request):

    context = {
        'reviews': Review.objects.recentReviews(),
        'books': Book.objects.all()
    }

    return render(request, 'books/index.html', context)

def new(request):

    context = {
        'authors': Author.objects.all()
    }

    return render(request, 'books/new.html', context)

def show(request, bookid):

    try:
        context = {
            'bookid': bookid,
            'reviews': Review.objects.filter(book_id=bookid),
            'book': Book.objects.get(id=bookid)
        }

        return render(request, 'books/show.html', context)
    except:
        error = "We have encountered a problem showing the book. Please contact an administrator"
        messages.error(request, error)
        return redirect('books:index')


def createBook(request):
    if 'loggedIn' not in request.session:
        request.session['loggedIn'] = False
        return redirect('main:index')


    if request.method == 'POST':
        newBook = request.POST


        authorInfo = {
            'existingauthors': newBook['existingauthors'],
            'newauthor': newBook['newauthor']
        }
        errors = Author.objects.authorValidate(authorInfo)
        if errors:
            for error in errors:
                messages.error(request, error)
            return redirect('books:new')
        if newBook['existingauthors'] == "addauthor":
            authorInfo['name'] = newBook['newauthor']
        else:
            authorInfo['name'] = newBook['existingauthors']
        authorInfo.pop('existingauthors', None)
        authorInfo.pop('newauthor', None)



        bookInfo = {
            'title': newBook['title'],
            'author': authorInfo['name']
        }
        errors = Book.objects.bookValidate(bookInfo)
        if errors:
            for error in errors:
                messages.error(request, error)
            return redirect('books:new')


        reviewInfo = {

            'review': newBook['review'],
            'rating': int(newBook['rating'])
        }
        errors = Review.objects.reviewValidate(reviewInfo)
        if errors:
            for error in errors:
                messages.error(request, error)
            return redirect('books:new')



        Author.objects.addAuthor(authorInfo)
        Book.objects.addBook(bookInfo)
        reviewInfo['book'] = Book.objects.last()
        reviewInfo['reviewer'] = request.session['userid']
        Review.objects.addReview(reviewInfo)

    addedBook = Book.objects.last()
    bookid = addedBook.id
    return redirect('books:show', bookid)


def addReview(request, bookid):
    review = request.POST
    reviewInfo = {
        'reviewer': request.session['userid'],
        'book': Book.objects.get(id=bookid),
        'rating': review['rating'],
        'review': review['review']
    }

    errors = Review.objects.reviewValidate(reviewInfo)
    if errors:
        for error in errors:
            messages.error(request, error)
        return redirect('books:show', bookid)


    Review.objects.addReview(reviewInfo)
    return redirect('books:show', bookid)   

def deleteReview(request, bookid, reviewid):
    Review.objects.deleteReview(reviewid)
    
    return redirect('books:show', bookid)

Python/Django/booklover/apps/books/templates/books/index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Book Lovers</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'books/css/navbar.css' %}">
    <link rel="stylesheet" href="{% static 'books/css/main.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'books:index' %}">Book Lover</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active"><a class="nav-link" href="{% url 'books:index' %}">Home</a></li>
                <li class="nav-item active"><a class="nav-link" href="{% url 'books:new' %}">Add Book and Review</a></li>
            </ul>
            
            <a class="d-inline my-2 my-md-0 add text-white">Welcome, {{request.session.first_name}}</a>
            {% if request.session.loggedIn %}
                <a class="d-inline my-2 my-md-0 text-white" href="{% url 'main:logout' %}">Logout</a>
            {% endif %}
        </div>
    </nav>
    <div class="container">
        <div class="recentreviews d-inline-block">
            <h5>Recent Book Reviews</h5>
            <div class="books">
                {% for review in reviews %}
                    <a href="{% url 'books:show' review.book.id %}">{{review.book.title}}</a>
                    <p>Rating: {{review.rating}} Stars </p>
                    <p>{{review.reviewer.first_name}} says "{{review.review}}"</p>
                {% endfor %}
            </div>
        </div>
        <div class="otherbooks d-inline-block">
            <h5>Other Books with Reviews:</h5>
            <div class="booklist">
                <ul>
                    {% for book in books %}
                        <li><a href="{% url 'books:show' book.id %}">{{book.title}}</a></li>
                    {% endfor %}
                </ul>
            </div>
            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}

        </div>
    </div>



</body>
</html>

Python/Django/booklover/apps/books/templates/books/new.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Book Lovers</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'books/css/navbar.css' %}">
    <link rel="stylesheet" href="{% static 'books/css/new.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'books:index' %}">Book Lover</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active"><a class="nav-link" href="{% url 'books:index' %}">Home</a></li>
                <li class="nav-item active"><a class="nav-link">Hello, {{request.session.first_name}}</a></li>
            </ul>
            <a class="d-inline my-2 my-md-0 add text-white" href="#">Add Book and Review</a>
            {% if request.session.loggedIn %}
                <a class="d-inline my-2 my-md-0 text-white" href="{% url 'main:logout' %}">Logout</a>
            {% endif %}
        </div>
    </nav>
    
    
    <div class="container">
        <h4>Add a New Book Tital and a Review:</h4>
        <form action="{% url 'books:create' %}" method="POST">
            <div class="form-group">
                <label for="title">Book Title:</label>
                <input type="text" name="title" id="title" class="form-control">
            </div>
            <label>Author: </label>
            <div class="form-group authoroptions">
                <label for="existingauthors">Choose from the list:</label>
                <select name="existingauthors" id="existingauthors" class="form-control">
                    <option value="addauthor">--add a new author--</option>
                    {% for author in authors %}
                        <option value="{{author.name}}">{{author.name}}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group authoroptions">
                <label for="newauthor">Or add a new author:</label>
                <input type="text" name="newauthor" id="newauthor" class="form-control">
            </div>
            <div class="form-group">
                <label for="review">Review:</label>
                <textarea name="review" id="review" class="form-control"></textarea>
            </div>
            <div class="form-group">
                <label for="rating">Rating:</label>
                <select name="rating" id="rating">
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>                    
                </select>
            </div>
            <div class="form-group float-right">
                <button class="btn btn-outline-dark">Add Book and Review</button>
            </div>
            {% csrf_token %}
        </form>
        {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                    <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>
</body>
</html>

Python/Django/booklover/apps/books/templates/books/show.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Book Lovers</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'books/css/navbar.css' %}">
    <link rel="stylesheet" href="{% static 'books/css/show.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'books:index' %}">Book Lover</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active"><a class="nav-link" href="{% url 'books:index' %}">Home</a></li>
                <li class="nav-item active"><a class="nav-link">Welcome, {{request.session.first_name}}</a></li>
            </ul>
            <a class="d-inline my-2 my-md-0 add text-white" href="{% url 'books:new' %}">Add Book and Review</a>
            {% if request.session.loggedIn %}
                <a class="d-inline my-2 my-md-0 text-white" href="{% url 'main:logout' %}">Logout</a>
            {% endif %}
        </div>
    </nav>
    
    
    <div class="container col-11">
        <div class="book d-inline-block">
            <h4>{{book.title}}</h4>
            <h6>Author: {{book.author.name}}</h6>
            <h5>Reviews:</h5>
            <hr>
            {% for review in reviews %}
            <div class="review">
                <p class="d-inline">Rating: {{review.rating}} Stars</p>
                {% if review.reviewer.id == request.session.userid %}
                    <p class="d-inline"><a href="{% url 'books:destroy' review.book.id review.id %}">Delete Review</a></p>
                {% endif %}
                <p class="">
                    <a href="{% url 'main:show' review.reviewer.id %}" class="d-inline">{{review.reviewer.first_name}}</a> says "{{review.review}}"
                </p>
                <p>Posted on {{review.created_at}}</p>
            </div>
            <hr>
            {% endfor %}
        </div>
        <div class="addreview d-inline-block">
            <h5>Other Books with Reviews:</h5>
            <form action="{% url 'books:addReview' bookid %}" method="POST">
                <div class="form-group">
                    <label for="review">Add a Review:</label>
                    <textarea name="review" id="review" class="form-control"></textarea>
                </div>
                <div class="form-group">
                    <label for="rating">Rating:</label>
                    <select name="rating" id="rating">
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                    </select>
                    <p class="d-inline">stars</p>
                </div>
                <div class="form-group float-right">
                    <button type="submit" class="btn btn-outline-dark">Submit Review</button>
                </div>
                {% csrf_token %}
            </form>
            {% if messages %}
                <ul class="messages">
                    {% for message in messages %}
                        <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}
        </div>
    </div>
</body>
</html>